name: Test Workflow
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        echo "Running tests..."
        # Aquí puedes agregar el comando o script para ejecutar tus pruebas.
